# Generated by Django 2.2 on 2020-09-11 15:50

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200911_2056'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
