# Generated by Django 2.2 on 2020-08-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(default='new', max_length=40, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TO_DO_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=3000, verbose_name='Описание')),
                ('long_description', models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Описание подробное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.Issues', verbose_name='Тип задачи')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='webapp.Statuses', verbose_name='Статус')),
            ],
        ),
    ]
