# Generated by Django 2.2 on 2020-07-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='TO_DO_List',
        ),
    ]
