# Generated by Django 2.2 on 2020-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_do_list',
            old_name='long_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='issues',
            name='issue',
            field=models.CharField(max_length=40, verbose_name='Статус'),
        ),
    ]
