# Generated by Django 2.2 on 2020-08-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200804_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_do_list',
            old_name='issue',
            new_name='issue_old',
        ),
    ]
