# Generated by Django 2.2 on 2020-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200721_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='deadline',
            field=models.DateField(default='0001-01-01', verbose_name='Дата выполнения'),
        ),
    ]
