# Generated by Django 2.2 on 2020-08-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200806_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='issue',
            field=models.ManyToManyField(related_name='issueses', to='webapp.Issues', verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='issue_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_old', to='webapp.Issues', verbose_name='Тип задачи'),
        ),
    ]
