# Generated by Django 2.2 on 2020-08-06 18:00

from django.db import migrations


def transfer_tags(apps, schema_editor):
    TO_DO_List = apps.get_model('webapp.TO_DO_List')
    for to_do_action in TO_DO_List.objects.all():
        to_do_action.issue.add(to_do_action.issue_old)


def rollback_transfer(apps, schema_editor):
    TO_DO_List = apps.get_model('webapp.TO_DO_List')
    for to_do_action in TO_DO_List.objects.all():
        to_do_action.issue_old.set(to_do_action.issue)


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0004_auto_20200806_2340'),
    ]

    operations = [
        migrations.RunPython(transfer_tags,
                             # rollback_transfer
                             )
    ]
