# Generated by Django 2.2 on 2020-07-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200721_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='deadline',
            field=models.DateField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default=None, null=True, verbose_name='Дата выполнения'),
        ),
    ]
