# Generated by Django 2.2 on 2020-08-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200807_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='issue_old',
        ),
    ]
