# Generated by Django 2.2 on 2020-08-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_to_do_list_issue_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_do_list', to='webapp.Statuses', verbose_name='Статус'),
        ),
    ]
