# Generated by Django 2.2 on 2020-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_to_do_list_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=40, verbose_name='Статус'),
        ),
    ]
