# Generated by Django 2.2 on 2020-08-10 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200807_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='summary',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание'),
        ),
    ]
