# Generated by Django 2.2 on 2020-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='begin_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
    ]
