# Generated by Django 2.2 on 2020-08-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20200821_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='webapp.Project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
