# Generated by Django 2.2 on 2020-09-07 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0016_auto_20200825_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Команда'),
        ),
    ]
