# Generated by Django 2.2 on 2020-09-08 17:40

import django.core.validators
from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, validators=[webapp.models.at_least_10], verbose_name='Описание подробное'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='issue',
            field=models.ManyToManyField(related_name='issueses', to='webapp.Issues', verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='summary',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание'),
        ),
    ]
