# Generated by Django 2.2 on 2020-09-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200908_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': {('can_change_team', 'может редактировать команду преокта')}},
        ),
    ]
